using System;

namespace POE
{
    public class AsciiArt
    {
        public static string GetLogo()
        {
            return @"
 ██╗    ██╗███████╗ █████╗ ██╗   ██╗███████╗██████╗
 ██║    ██║██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
 ██║ █╗ ██║█████╗  ███████║██║   ██║█████╗  ██████╔╝
 ██║███╗██║██╔══╝  ██╔══██║╚██╗ ██╔╝██╔══╝  ██╔══██╗
 ╚███╔███╔╝███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
        ░░  A W A R E N E S S   B O T  ░░
           ——  S T A Y   S A F E  ——
--------------------------------------------------
";
        }
    }
}